### ISSUE TITLE
PushPatternTest is testing old value?

### ISSUE THREAD

**Issue by Kantiran91** [Servicerobotics-Ulm/SmartSoftComponentDeveloperAPIcpp#5]
At Line 199 the value is set to 4 and is put on the server. At line 207 the value is readed as 4 but in Line 210 the value is expect as 3. Is there some reason why the value should not be 4? 

https://github.com/Servicerobotics-Ulm/SmartSoftComponentDeveloperAPIcpp/blob/d2b95e0d8f6a770a71e1a896d9f881e7ddd16ffe/gtests/SmartSoftTests/PushPatternTests.h#L199-L210

**Comment by alex-lotz** [comment]
Yes, the reason is that a few lines above, the client subscribed with the subdivider "2", which means that only every second update is received and consequently, update 4 would not be received by the client and the current value still must be 3.
